#!/usr/local/bin/python3 

import time 
import argparse
"""
Sets up and returns the parser
"""
def setup_parser():
    parser = argparse.ArgumentParser(description='Start and run a pomodoro timer')
    parser.add_argument('--study', type=int, default=25, help='The amount of time to study for')
    parser.add_argument('--rest', type=int, default=5, help='The amount of time for breaks')
    parser.add_argument('--loops', type=int, default=4, help='The number of loops to run through')
    return parser

"""
A countdown timer that takes in the number of seconds that it minutes that the timer
should run for.
"""
def countdown_timer(value, timer_type):
    t = value * 60
    while t != 0:
        mins, secs = divmod(t, 60)
        timer = 'Time remaining: {:02d}:{:02d}'.format(mins, secs)
        print(timer, end="\r")
        time.sleep(1)
        t -= 1
    print("{} complete!".format(timer_type))
    playsound('./chime.mp3')

def main(args):
    # Getting user input
    # Reading user input back to user
    study_time = args.study
    break_time = args.rest
    repeat_count = args.loops

    print("Okay, you're going to study for {} minutes and relax for {} minutes, and this will repeat {} times.".format(study_time, break_time, repeat_count))
     
    # Make these immutable, and multiply by 60 for minutes
    for _ in range(repeat_count):
        countdown_timer(study_time, "pomodoro")  
        countdown_timer(break_time, "break")
    print("You have completed your pomodoro session. Goodbye!")

if __name__ == "__main__":
    parser = setup_parser()
    main(parser.parse_args())
